### PR TITLE
[CUBRIDMAN-83] Migrate Travis-CI checks to Github Actions

### PR DESCRIPTION
**Pull request by hgryoo**
http://jira.cubrid.org/browse/CUBRIDMAN-83

- Add GitHub actions to build sphinx. The following tests will be performed.
  - syntax check
  - link check
- Remove the Travis-CI config file

Note that there is a broken link in Korean manual

### CODE REVIEW

**Review by mhoh3963 — APPROVED** [review]
good.

**Comment by mhoh3963** [comment]
@hgryoo please check occurring errors when building korean manual.

**Comment by hgryoo** [comment]
> @hgryoo please check occurring errors when building korean manual.

I noted in the description of this PR about the failure in the Korean manual :-) It should be fixed at another issue.

**Comment by mhoh3963** [comment]
> > @hgryoo please check occurring errors when building korean manual.
> 
> I noted in the description of this PR about the failure in the Korean manual :-) It should be fixed at another issue.

OK.

**Pull request merged**
